// <auto-generated />
using System;
using BarcodePos.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BarcodePos.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("BarcodePos.Domain.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("StoreId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("StoreId");

                    b.ToTable("Categories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Soğuk ve sıcak içecekler",
                            IsActive = true,
                            Name = "İçecekler",
                            StoreId = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Çikolata, cips, bisküvi",
                            IsActive = true,
                            Name = "Atıştırmalıklar",
                            StoreId = 1
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Ekmek, süt, yumurta, un",
                            IsActive = true,
                            Name = "Temel Gıda",
                            StoreId = 1
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Deterjan, sabun, kağıt ürünleri",
                            IsActive = true,
                            Name = "Temizlik",
                            StoreId = 1
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Şampuan, diş macunu, deodorant",
                            IsActive = true,
                            Name = "Kişisel Bakım",
                            StoreId = 1
                        });
                });

            modelBuilder.Entity("BarcodePos.Domain.Entities.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Balance")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue(0m);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("StoreId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("StoreId");

                    b.ToTable("Customers", (string)null);
                });

            modelBuilder.Entity("BarcodePos.Domain.Entities.CustomerTransaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("BalanceAfter")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("CustomerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int?>("SaleId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("SaleId");

                    b.ToTable("CustomerTransactions", (string)null);
                });

            modelBuilder.Entity("BarcodePos.Domain.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Barcode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("CostPrice")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MinStockLevel")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("SalePrice")
                        .HasColumnType("TEXT");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StoreId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("TaxRate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("StoreId", "Barcode")
                        .IsUnique();

                    b.ToTable("Products", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Barcode = "8690494017710",
                            CategoryId = 1,
                            CostPrice = 8.00m,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            MinStockLevel = 20,
                            Name = "Coca-Cola 330ml",
                            SalePrice = 12.50m,
                            StockQuantity = 200,
                            StoreId = 1,
                            TaxRate = 10m
                        },
                        new
                        {
                            Id = 2,
                            Barcode = "8690494017727",
                            CategoryId = 1,
                            CostPrice = 14.00m,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            MinStockLevel = 15,
                            Name = "Coca-Cola 1L",
                            SalePrice = 22.00m,
                            StockQuantity = 150,
                            StoreId = 1,
                            TaxRate = 10m
                        },
                        new
                        {
                            Id = 3,
                            Barcode = "8690637000508",
                            CategoryId = 1,
                            CostPrice = 2.00m,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            MinStockLevel = 50,
                            Name = "Erikli Su 500ml",
                            SalePrice = 5.00m,
                            StockQuantity = 500,
                            StoreId = 1,
                            TaxRate = 1m
                        },
                        new
                        {
                            Id = 4,
                            Barcode = "8690637000515",
                            CategoryId = 1,
                            CostPrice = 3.50m,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            MinStockLevel = 30,
                            Name = "Erikli Su 1.5L",
                            SalePrice = 7.50m,
                            StockQuantity = 300,
                            StoreId = 1,
                            TaxRate = 1m
                        },
                        new
                        {
                            Id = 5,
                            Barcode = "8690504550013",
                            CategoryId = 1,
                            CostPrice = 85.00m,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            MinStockLevel = 10,
                            Name = "Ã‡aykur Rize Ã‡ay 1kg",
                            SalePrice = 119.90m,
                            StockQuantity = 40,
                            StoreId = 1,
                            TaxRate = 10m
                        },
                        new
                        {
                            Id = 6,
                            Barcode = "8690632042008",
                            CategoryId = 1,
                            CostPrice = 3.50m,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            MinStockLevel = 20,
                            Name = "Nescafe 3in1",
                            SalePrice = 6.00m,
                            StockQuantity = 100,
                            StoreId = 1,
                            TaxRate = 10m
                        },
                        new
                        {
                            Id = 7,
                            Barcode = "8690504055501",
                            CategoryId = 2,
                            CostPrice = 5.00m,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            MinStockLevel = 15,
                            Name = "Ãœlker Ã‡ikolatalÄ± Gofret",
                            SalePrice = 8.50m,
                            StockQuantity = 120,
                            StoreId = 1,
                            TaxRate = 10m
                        },
                        new
                        {
                            Id = 8,
                            Barcode = "8690504055518",
                            CategoryId = 2,
                            CostPrice = 7.00m,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            MinStockLevel = 10,
                            Name = "Eti Canga",
                            SalePrice = 12.00m,
                            StockQuantity = 80,
                            StoreId = 1,
                            TaxRate = 10m
                        },
                        new
                        {
                            Id = 9,
                            Barcode = "8690624000016",
                            CategoryId = 2,
                            CostPrice = 15.00m,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            MinStockLevel = 10,
                            Name = "Doritos Cips 120g",
                            SalePrice = 24.90m,
                            StockQuantity = 60,
                            StoreId = 1,
                            TaxRate = 10m
                        },
                        new
                        {
                            Id = 10,
                            Barcode = "8690504011507",
                            CategoryId = 2,
                            CostPrice = 10.00m,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            MinStockLevel = 10,
                            Name = "Ãœlker Petit Beurre",
                            SalePrice = 16.50m,
                            StockQuantity = 90,
                            StoreId = 1,
                            TaxRate = 10m
                        },
                        new
                        {
                            Id = 11,
                            Barcode = "8690804000011",
                            CategoryId = 3,
                            CostPrice = 12.00m,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            MinStockLevel = 20,
                            Name = "SÃ¼t 1L (GÃ¼nlÃ¼k)",
                            SalePrice = 18.50m,
                            StockQuantity = 100,
                            StoreId = 1,
                            TaxRate = 1m
                        },
                        new
                        {
                            Id = 12,
                            Barcode = "8690804000028",
                            CategoryId = 3,
                            CostPrice = 35.00m,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            MinStockLevel = 10,
                            Name = "Yumurta 15'li",
                            SalePrice = 54.90m,
                            StockQuantity = 50,
                            StoreId = 1,
                            TaxRate = 1m
                        },
                        new
                        {
                            Id = 13,
                            Barcode = "8690804000035",
                            CategoryId = 3,
                            CostPrice = 8.00m,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            MinStockLevel = 5,
                            Name = "Ekmek (Tam BuÄŸday)",
                            SalePrice = 12.00m,
                            StockQuantity = 30,
                            StoreId = 1,
                            TaxRate = 1m
                        },
                        new
                        {
                            Id = 14,
                            Barcode = "8690804000042",
                            CategoryId = 3,
                            CostPrice = 20.00m,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            MinStockLevel = 8,
                            Name = "Un 2kg (Sinangil)",
                            SalePrice = 32.50m,
                            StockQuantity = 40,
                            StoreId = 1,
                            TaxRate = 1m
                        },
                        new
                        {
                            Id = 15,
                            Barcode = "8690804000059",
                            CategoryId = 3,
                            CostPrice = 14.00m,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            MinStockLevel = 10,
                            Name = "Åeker 1kg",
                            SalePrice = 22.90m,
                            StockQuantity = 60,
                            StoreId = 1,
                            TaxRate = 1m
                        },
                        new
                        {
                            Id = 16,
                            Barcode = "8690506000011",
                            CategoryId = 4,
                            CostPrice = 25.00m,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            MinStockLevel = 10,
                            Name = "Fairy BulaÅŸÄ±k Det. 500ml",
                            SalePrice = 39.90m,
                            StockQuantity = 45,
                            StoreId = 1,
                            TaxRate = 20m
                        },
                        new
                        {
                            Id = 17,
                            Barcode = "8690506000028",
                            CategoryId = 4,
                            CostPrice = 22.00m,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            MinStockLevel = 8,
                            Name = "Domestos 750ml",
                            SalePrice = 36.50m,
                            StockQuantity = 35,
                            StoreId = 1,
                            TaxRate = 20m
                        },
                        new
                        {
                            Id = 18,
                            Barcode = "8690506000035",
                            CategoryId = 4,
                            CostPrice = 55.00m,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            MinStockLevel = 5,
                            Name = "Selpak Tuvalet KaÄŸÄ±dÄ± 16lÄ±",
                            SalePrice = 84.90m,
                            StockQuantity = 25,
                            StoreId = 1,
                            TaxRate = 20m
                        },
                        new
                        {
                            Id = 19,
                            Barcode = "8690506500017",
                            CategoryId = 5,
                            CostPrice = 45.00m,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            MinStockLevel = 5,
                            Name = "Head&Shoulders 400ml",
                            SalePrice = 69.90m,
                            StockQuantity = 30,
                            StoreId = 1,
                            TaxRate = 20m
                        },
                        new
                        {
                            Id = 20,
                            Barcode = "8690506500024",
                            CategoryId = 5,
                            CostPrice = 18.00m,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            MinStockLevel = 10,
                            Name = "Colgate DiÅŸ Macunu 75ml",
                            SalePrice = 29.90m,
                            StockQuantity = 50,
                            StoreId = 1,
                            TaxRate = 20m
                        });
                });

            modelBuilder.Entity("BarcodePos.Domain.Entities.Sale", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CustomerId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("DiscountTotal")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("GrandTotal")
                        .HasColumnType("TEXT");

                    b.Property<int>("PaymentType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ReceiptNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("SaleDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StoreId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("SubTotal")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TaxTotal")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("ReceiptNumber")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.HasIndex("StoreId", "SaleDate");

                    b.ToTable("Sales", (string)null);
                });

            modelBuilder.Entity("BarcodePos.Domain.Entities.SaleItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Barcode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CostPrice")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("DiscountAmount")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("LineTotal")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SaleId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("TaxRate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("SaleId");

                    b.ToTable("SaleItems", (string)null);
                });

            modelBuilder.Entity("BarcodePos.Domain.Entities.StockMovement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StockAfter")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("ProductId", "CreatedAt");

                    b.ToTable("StockMovements", (string)null);
                });

            modelBuilder.Entity("BarcodePos.Domain.Entities.Store", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Stores", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Ana Mağaza"
                        });
                });

            modelBuilder.Entity("BarcodePos.Domain.Entities.Subscription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PlanId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartsAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("WebCustomerId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PlanId");

                    b.HasIndex("WebCustomerId");

                    b.ToTable("Subscriptions");
                });

            modelBuilder.Entity("BarcodePos.Domain.Entities.SubscriptionPlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("DurationDays")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasBackup")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasReports")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasSupport")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxProducts")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxUsers")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("SubscriptionPlans");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DurationDays = 14,
                            HasBackup = false,
                            HasReports = false,
                            HasSupport = false,
                            IsActive = true,
                            MaxProducts = 50,
                            MaxUsers = 1,
                            Name = "Demo",
                            Price = 0m,
                            Slug = "demo"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DurationDays = 30,
                            HasBackup = true,
                            HasReports = true,
                            HasSupport = true,
                            IsActive = true,
                            MaxProducts = 2147483647,
                            MaxUsers = 3,
                            Name = "Profesyonel",
                            Price = 299m,
                            Slug = "pro"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DurationDays = 365,
                            HasBackup = true,
                            HasReports = true,
                            HasSupport = true,
                            IsActive = true,
                            MaxProducts = 2147483647,
                            MaxUsers = 2147483647,
                            Name = "Kurumsal",
                            Price = 0m,
                            Slug = "enterprise"
                        });
                });

            modelBuilder.Entity("BarcodePos.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StoreId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.HasIndex("StoreId", "Username")
                        .IsUnique();

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FullName = "Sistem Yöneticisi",
                            IsActive = true,
                            PasswordHash = "$2a$11$GBrDulOzslTYDkE9UmrYg.eyFLfqWXNkYE4g9Qn7HMxnFyDy198AK",
                            Role = 1,
                            StoreId = 1,
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("BarcodePos.Domain.Entities.WebCustomer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BusinessName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EmailConfirmExpiry")
                        .HasColumnType("TEXT");

                    b.Property<string>("EmailConfirmToken")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("PasswordResetExpiry")
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordResetToken")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("StoreId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("StoreId");

                    b.ToTable("WebCustomers");
                });

            modelBuilder.Entity("BarcodePos.Domain.Entities.Category", b =>
                {
                    b.HasOne("BarcodePos.Domain.Entities.Store", "Store")
                        .WithMany("Categories")
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Store");
                });

            modelBuilder.Entity("BarcodePos.Domain.Entities.Customer", b =>
                {
                    b.HasOne("BarcodePos.Domain.Entities.Store", "Store")
                        .WithMany("Customers")
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Store");
                });

            modelBuilder.Entity("BarcodePos.Domain.Entities.CustomerTransaction", b =>
                {
                    b.HasOne("BarcodePos.Domain.Entities.Customer", "Customer")
                        .WithMany("Transactions")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BarcodePos.Domain.Entities.Sale", "Sale")
                        .WithMany("CustomerTransactions")
                        .HasForeignKey("SaleId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Customer");

                    b.Navigation("Sale");
                });

            modelBuilder.Entity("BarcodePos.Domain.Entities.Product", b =>
                {
                    b.HasOne("BarcodePos.Domain.Entities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BarcodePos.Domain.Entities.Store", "Store")
                        .WithMany("Products")
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Store");
                });

            modelBuilder.Entity("BarcodePos.Domain.Entities.Sale", b =>
                {
                    b.HasOne("BarcodePos.Domain.Entities.Customer", "Customer")
                        .WithMany("Sales")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BarcodePos.Domain.Entities.Store", "Store")
                        .WithMany("Sales")
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BarcodePos.Domain.Entities.User", "User")
                        .WithMany("Sales")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Store");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BarcodePos.Domain.Entities.SaleItem", b =>
                {
                    b.HasOne("BarcodePos.Domain.Entities.Product", "Product")
                        .WithMany("SaleItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BarcodePos.Domain.Entities.Sale", "Sale")
                        .WithMany("Items")
                        .HasForeignKey("SaleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Sale");
                });

            modelBuilder.Entity("BarcodePos.Domain.Entities.StockMovement", b =>
                {
                    b.HasOne("BarcodePos.Domain.Entities.Product", "Product")
                        .WithMany("StockMovements")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BarcodePos.Domain.Entities.User", "User")
                        .WithMany("StockMovements")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BarcodePos.Domain.Entities.Subscription", b =>
                {
                    b.HasOne("BarcodePos.Domain.Entities.SubscriptionPlan", "Plan")
                        .WithMany("Subscriptions")
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BarcodePos.Domain.Entities.WebCustomer", "WebCustomer")
                        .WithMany("Subscriptions")
                        .HasForeignKey("WebCustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plan");

                    b.Navigation("WebCustomer");
                });

            modelBuilder.Entity("BarcodePos.Domain.Entities.User", b =>
                {
                    b.HasOne("BarcodePos.Domain.Entities.Store", "Store")
                        .WithMany("Users")
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Store");
                });

            modelBuilder.Entity("BarcodePos.Domain.Entities.WebCustomer", b =>
                {
                    b.HasOne("BarcodePos.Domain.Entities.Store", "Store")
                        .WithMany()
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Store");
                });

            modelBuilder.Entity("BarcodePos.Domain.Entities.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("BarcodePos.Domain.Entities.Customer", b =>
                {
                    b.Navigation("Sales");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("BarcodePos.Domain.Entities.Product", b =>
                {
                    b.Navigation("SaleItems");

                    b.Navigation("StockMovements");
                });

            modelBuilder.Entity("BarcodePos.Domain.Entities.Sale", b =>
                {
                    b.Navigation("CustomerTransactions");

                    b.Navigation("Items");
                });

            modelBuilder.Entity("BarcodePos.Domain.Entities.Store", b =>
                {
                    b.Navigation("Categories");

                    b.Navigation("Customers");

                    b.Navigation("Products");

                    b.Navigation("Sales");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("BarcodePos.Domain.Entities.SubscriptionPlan", b =>
                {
                    b.Navigation("Subscriptions");
                });

            modelBuilder.Entity("BarcodePos.Domain.Entities.User", b =>
                {
                    b.Navigation("Sales");

                    b.Navigation("StockMovements");
                });

            modelBuilder.Entity("BarcodePos.Domain.Entities.WebCustomer", b =>
                {
                    b.Navigation("Subscriptions");
                });
#pragma warning restore 612, 618
        }
    }
}
